# Generated by Django 4.0.3 on 2022-03-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tx_title', max_length=64)),
                ('description', models.TextField(db_column='tx_description', max_length=256)),
                ('value', models.FloatField(blank=True, db_column='fl_value', default=0.0, null=True)),
                ('ong_id', models.ForeignKey(db_column='ong_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ong.ong')),
            ],
            options={
                'db_table': 'case',
                'managed': True,
            },
        ),
    ]
