# Generated by Django 4.0.3 on 2022-03-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_alter_ong_options_alter_ong_table'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='case',
            name='ong_id',
            field=models.ForeignKey(db_column='ong_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ong.ong'),
        ),
        migrations.AlterModelTable(
            name='case',
            table='case',
        ),
    ]
