# Generated by Django 4.0.3 on 2022-03-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', max_length=64)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('number', models.CharField(db_column='tx_number', max_length=32)),
                ('city', models.CharField(db_column='tx_city', max_length=64)),
                ('region', models.CharField(db_column='tx_region', max_length=2)),
                ('code', models.CharField(blank=True, db_column='tx_code', max_length=8, null=True)),
            ],
            options={
                'db_table': 'ong',
                'managed': True,
            },
        ),
    ]
