# Generated by Django 3.1.6 on 2022-03-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=64)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('number', models.CharField(db_column='tx_number', max_length=32)),
                ('city', models.CharField(db_column='tx_city', max_length=64)),
                ('region', models.CharField(db_column='tx_region', max_length=2)),
            ],
        ),
    ]
