# Generated by Django 4.0.3 on 2022-03-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ong',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='ong',
            table='ong',
        ),
    ]
