# Generated by Django 4.0.3 on 2022-03-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_alter_ong_options_alter_ong_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
