# Generated by Django 3.1.6 on 2022-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_alter_ong_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='code',
            field=models.CharField(blank=True, db_column='tx_code', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
